name: Fuzz Test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  fuzztest:
    name: Fuzz Test
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_fuzztest
      CLANG_VERSION: 15

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: 'True'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y    \
            "clang-${CLANG_VERSION}" \
            cmake                    \
            ninja-build

      - name: Configure
        run: |
          mkdir "$BUILD_DIR"
          cmake                                            \
            -S .                                           \
            -B "$BUILD_DIR"                                \
            -G Ninja                                       \
            -D CMAKE_BUILD_TYPE=RelWithDebug               \
            -D CMAKE_CXX_COMPILER="clang++-$CLANG_VERSION" \
            -D CMAKE_C_COMPILER="clang-$CLANG_VERSION"     \
            -D PSTORE_FUZZTEST=Yes

      - name: Build
        run: |
          ninja -C "$BUILD_DIR"

      - name: Fuzz
        run: |
          find "$BUILD_DIR" -name \*-unit-tests -type f -perm -u=x -exec {} --fuzz_for 10s \;

