name: KLEE Test
on:
    push:
        branches: [ klee ]
    pull_request:
        branches: [ klee ]
    workflow_dispatch:
permissions:
  contents: read

jobs:
    klee-test:
        runs-on: ubuntu-latest
        container:
            image: klee/klee:2.1
            options: -u 0 --ulimit="stack=-1:-1"
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                submodules: 'True'

            - name: Create Build Environment
              run: cmake -E make_directory "${{ github.workspace }}/build"

            - name: Configure
              run: |
                  cd "${{ github.workspace }}/build"
                  cmake -G "Unix Makefiles"             \
                        -D CMAKE_BUILD_TYPE=Debug       \
                        -D CMAKE_CXX_COMPILER=clang++   \
                        -D CMAKE_C_COMPILER=clang       \
                        -D PSTORE_BITCODE=Yes           \
                        -D PSTORE_DISABLE_UINT128_T=Yes \
                        -D PSTORE_EXAMPLES=No           \
                        -D PSTORE_EXCEPTIONS=No         \
                        "$GITHUB_WORKSPACE"

            - name: Build
              run: |
                  cd "${{ github.workspace }}/build"
                  cmake --build . --target pstore-klee-run-all
