name: KLEE Test
on:
    push:
        branches: [ klee ]
    pull_request:
        branches: [ klee ]
    workflow_dispatch:
permissions:
  contents: read

jobs:
    klee-test:
        runs-on: ubuntu-latest
        container:
            image: klee/klee:2.1
            options: -u 0 --ulimit="stack=-1:-1"
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
              with:
                submodules: 'True'

            - name: Create Build Environment
              run: cmake -E make_directory "${{ github.workspace }}/build"

            - name: Configure
              run: |
                  cd "${{ github.workspace }}/build"
                  cmake -G "Unix Makefiles"             \
                        -D CMAKE_BUILD_TYPE=Debug       \
                        -D CMAKE_CXX_COMPILER=clang++   \
                        -D CMAKE_C_COMPILER=clang       \
                        -D PSTORE_BITCODE=Yes           \
                        -D PSTORE_DISABLE_UINT128_T=Yes \
                        -D PSTORE_EXAMPLES=No           \
                        -D PSTORE_EXCEPTIONS=No         \
                        "$GITHUB_WORKSPACE"

            - name: Build
              run: |
                  cd "${{ github.workspace }}/build"
                  cmake --build . --target pstore-klee-run-all
